version: '3.4'

services:
  botapi:
    image: elment/voicecontrol
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - "elment/voicecontrol:latest"
    volumes: 
      - ./:/app
    environment: 
      - user=${user}