version: '3.4'

services:
  voicecontrol:
    image: elment/voicecontrol
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - "elment/voicecontrol:latest"
    volumes: 
      - ./src:/app
    # environment: 
      # - user=${user}